
package com.viettel.mobileca.signature.apservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "APWsImplService", targetNamespace = "http://ws.apservice.viettel.com/", wsdlLocation = "http://10.60.15.217:8084/apws.asmx?wsdl")
public class APWsImplService
    extends Service
{

    private final static URL APWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException APWSIMPLSERVICE_EXCEPTION;
    private final static QName APWSIMPLSERVICE_QNAME = new QName("http://ws.apservice.viettel.com/", "APWsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.60.15.217:8084/apws.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APWSIMPLSERVICE_WSDL_LOCATION = url;
        APWSIMPLSERVICE_EXCEPTION = e;
    }

    public APWsImplService() {
        super(__getWsdlLocation(), APWSIMPLSERVICE_QNAME);
    }

    public APWsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APWSIMPLSERVICE_QNAME, features);
    }

    public APWsImplService(URL wsdlLocation) {
        super(wsdlLocation, APWSIMPLSERVICE_QNAME);
    }

    public APWsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APWSIMPLSERVICE_QNAME, features);
    }

    public APWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public APWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns APWs
     */
    @WebEndpoint(name = "APWsImplPort")
    public APWs getAPWsImplPort() {
        return super.getPort(new QName("http://ws.apservice.viettel.com/", "APWsImplPort"), APWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APWs
     */
    @WebEndpoint(name = "APWsImplPort")
    public APWs getAPWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.apservice.viettel.com/", "APWsImplPort"), APWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APWSIMPLSERVICE_EXCEPTION!= null) {
            throw APWSIMPLSERVICE_EXCEPTION;
        }
        return APWSIMPLSERVICE_WSDL_LOCATION;
    }

}
