
package com.viettel.mobileca.signature.apservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "APWs", targetNamespace = "http://ws.apservice.viettel.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface APWs {


    /**
     * 
     * @param tranInfo
     * @return
     *     returns com.viettel.apservice.TransactionInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.apservice.viettel.com/APWs/signatureRequest", output = "http://ws.apservice.viettel.com/APWs/signatureResponse")
    public TransactionInfo signature(
        @WebParam(name = "tranInfo", partName = "tranInfo")
        TransactionInfo tranInfo);

    /**
     * 
     * @param tranInfo
     * @return
     *     returns com.viettel.apservice.TransactionInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.apservice.viettel.com/APWs/connectRequest", output = "http://ws.apservice.viettel.com/APWs/connectResponse")
    public TransactionInfo connect(
        @WebParam(name = "tranInfo", partName = "tranInfo")
        TransactionInfo tranInfo);

    /**
     * 
     * @param tranInfo
     * @return
     *     returns com.viettel.apservice.TransactionInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.apservice.viettel.com/APWs/notificationRequest", output = "http://ws.apservice.viettel.com/APWs/notificationResponse")
    public TransactionInfo notification(
        @WebParam(name = "tranInfo", partName = "tranInfo")
        TransactionInfo tranInfo);

    /**
     * 
     * @param tranInfo
     * @return
     *     returns com.viettel.apservice.TransactionInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.apservice.viettel.com/APWs/certificateQueryRequest", output = "http://ws.apservice.viettel.com/APWs/certificateQueryResponse")
    public TransactionInfo certificateQuery(
        @WebParam(name = "tranInfo", partName = "tranInfo")
        TransactionInfo tranInfo);

    /**
     * 
     * @param tranInfo
     * @return
     *     returns com.viettel.apservice.TransactionInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.apservice.viettel.com/APWs/receiptRequest", output = "http://ws.apservice.viettel.com/APWs/receiptResponse")
    public TransactionInfo receipt(
        @WebParam(name = "tranInfo", partName = "tranInfo")
        TransactionInfo tranInfo);

    /**
     * 
     * @param tranInfo
     * @return
     *     returns com.viettel.apservice.TransactionInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.apservice.viettel.com/APWs/cancelSignatureRequest", output = "http://ws.apservice.viettel.com/APWs/cancelSignatureResponse")
    public TransactionInfo cancelSignature(
        @WebParam(name = "tranInfo", partName = "tranInfo")
        TransactionInfo tranInfo);

    /**
     * 
     * @param tranInfo
     * @return
     *     returns com.viettel.apservice.TransactionInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.apservice.viettel.com/APWs/statusQueryRequest", output = "http://ws.apservice.viettel.com/APWs/statusQueryResponse")
    public TransactionInfo statusQuery(
        @WebParam(name = "tranInfo", partName = "tranInfo")
        TransactionInfo tranInfo);

}
